### ISSUE TITLE
The dataset HyRANK-Loukia (HR-L) can't be downloaded now.

### ISSUE THREAD

**Issue by flyzzie** [MeiShaohui/Group-Aware-Hierarchical-Transformer#2]
[HyRANK-Loukia (HR-L)](https://www2.isprs.org/commissions/comm3/wg4/hyrank/)
This link is invalid.

**Comment by psychAo** [comment]
Thanks for raising the issue.
HR-L dataset can be downloaded in the following link:
https://zenodo.org/record/1222202#.Y4HMDn1Bxdh

**Comment by flyzzie** [comment]
Thank you so much!
